language: c
compiler:
  - gcc

env:
  global:
    - secure: "QfAjtgV7GrQViFNVEiqyM6GqjYybVnKXcNAvFkHDIq3+fgIUwUjECEw6GI7FjjsmknlQYBIx3ZBgdzaHKlYi3v7WFljdZwbFLVrcdEIBLfNkazu23vPfQ8OzDbvIVnjooawobEVJOtodq+YVeyDXdmXJSLsBg1eGE6JG2Pl7tRbOZjAShcL1U0nfSuvEA5ewoxHzcRdLwxBzcsyqhrseviJl8j1cvzaq8bWVyUoVZFNob4BP89eHbGlEOa56Zw7XGH4ld1e8EZ7G3K00efw8FlwYMePJx76MAJi0GSlY0QSJ0klfPx2E+0UP8rm+zmCkGqXBp27/ATIzhatY/evrxZMGKk2GQC1tcZGiv7JxJLqaj1c6ydvbiQunQUOpem10W6cZmpbPsEQf2lC6GHpWVKkkw1bKGuTKdOeltjQJ9ocwrFK97UxTXjcEMwVLy5yQvR1hEY60B6KTu1NUc3jwdUc4lu5r4iLuFC16fgUz/5nZXqZlcRjmyxfJvN418bVpwZHOazGCM6i9Xobt3JS7g7as9L8FoXUkbui1QuFVoCfmvBjb6HbPdibSIovSN1xVTh/VXxWC1nDyAGKKnkGB51tbHiqhh6LTGHFf4xtK3NDJAq32dkoVVHwfID+QwFHU9inWumbEGoVrOCEfqAQNguOJtJidPFVgaiWSDZCVJW8="

addons:
  coverity_scan:
    project:
      name: "dtikhonov/ls-qpack"
      description: "QPACK compression library"
    notification_email: dtikhonov@litespeedtech.com
    build_command_prepend: "cmake ."
    build_command: make
    branch_pattern: coverity_scan

before_install:
  - export PROJECT_NAME=dtikhonov/ls-qpack
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:
  - cmake -DLSQPACK_TESTS=ON .
  - make
  - make test
